version: "3"
services:
  video_creator:
    build: .
    image: anicklaus/social-media-news
    volumes:
      - ./out:/usr/src/app/out
      - ./sources:/usr/src/app/sources
      - ./google:/usr/src/app/google
    env_file:
    - .env