name: Videocreator

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Google Cloud credentials file
        run: mkdir ./google && touch ./google/credentials.json

      - name: Save Google Cloud credentials
        run: echo $GCLOUD_CREDENTIALS > ./google/credentials.json
        env:
          GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}

      - name: Test
        run: cat google/credentials.json

      - name: Start container
        run: docker run --name video-creator -v $(pwd)/google:/usr/src/app/google -e "GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/google/credentials.json" -e "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}" -e "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" -e "NYT_API_KEY=${{ secrets.NYT_API_KEY }}" -e "GMAIL_SENDER_ADDRESS=${{ secrets.GMAIL_SENDER_ADDRESS }}" -e "GMAIL_RECEIVER_ADDRESS=${{ secrets.GMAIL_RECEIVER_ADDRESS }}" -e "GMAIL_ACCESS_TOKEN=${{ secrets.GMAIL_ACCESS_TOKEN }}" anicklaus/social-media-news
