name: Videocreator

on:
  # schedule:
  #   - cron: "0 3 * * *"
  workflow_dispatch:

jobs:

  createStory:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Start container
        run: docker run --rm -v ./out:/usr/src/app/out/ -e "NYT_API_KEY=${{ secrets.NYT_API_KEY }}" anicklaus/social-media-news python src/getStory.py
      - name: List Output
        run: ls -al ./out
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: out-directory
          path: ./out/
          if-no-files-found: error
          
  createAudioFile:
    runs-on: ubuntu-latest
    needs: createStory
            
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: out-directory
          path: ./out/
      - name: Create Voice Audio File
        # run: docker-compose up tts
        run: docker run --rm -v ./out:/out --entrypoint="/bin/bash" ghcr.io/coqui-ai/tts-cpu  -c 'tts --text "$(cat /out/audio_text.txt)" --out_path "/out/tts.wav"'
      - name: List Output
        run: ls -al ./out
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: audio-file
          path: ./out/tts.wav
          if-no-files-found: error
  
  createVideo:
    runs-on: ubuntu-latest
    needs: [createStory, createAudioFile]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          path: ./out/
          merge-multiple: true
      - name: Start container
        run: docker run --rm -v ./out:/usr/src/app/out/ -e "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}" -e "GMAIL_SENDER_ADDRESS=${{ secrets.GMAIL_SENDER_ADDRESS }}" -e "GMAIL_RECEIVER_ADDRESS=${{ secrets.GMAIL_RECEIVER_ADDRESS }}" -e "GMAIL_ACCESS_TOKEN=${{ secrets.GMAIL_ACCESS_TOKEN }}" -e "IG_ACCESS_TOKEN=${{ secrets.IG_ACCESS_TOKEN }}" anicklaus/social-media-news python src/createVideo.py
